cache:
  paths:
    - vendor/bundle

before_script:
  - gem update --system
  - gem install bundler

variables:
  SKYLIGHT_EXT_STRICT: "false"
  SKYLIGHT_REQUIRED: "true"
  SKYLIGHT_ENABLE_TRACE_LOGS: "true"
  SKYLIGHT_TEST_DIR: "/tmp"
  RAILS_ENV: "development"
  EMBEDDED_HTTP_SERVER_TIMEOUT: "30"
  WORKER_SPAWN_TIMEOUT: "15"
  # COVERAGE: true # FIXME

.run_tests: &run_tests
  script:
    - pushd skylight-core
    - bundle install --path ../vendor/bundle
    - bundle exec rake
    - SKYLIGHT_DISABLE_AGENT=true bundle exec rake
    - popd
    - bundle install --path vendor/bundle
    - bundle exec rake
    - SKYLIGHT_DISABLE_AGENT=true bundle exec rake

stages:
  - focus
  - sanity
  - test
  - wrapup

sanity:
  <<: *run_tests
  stage: sanity
  image: ruby:2.6
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.rails-5.2.x

ruby23-rails42:
  <<: *run_tests
  stage: test
  image: ruby:2.3
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.rails-4.2.x

ruby26-rails42:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.rails-4.2.x

ruby23-rails52:
  <<: *run_tests
  stage: test
  image: ruby:2.3
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.rails-5.2.x

ruby26-rails50:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.rails-5.0.x

ruby26-rails51:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.rails-5.1.x

ruby26-rails-edge:
  <<: *run_tests
  stage: test
  allow_failure: true
  image: ruby:2.6
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.rails-edge

ruby23-sinatra14:
  <<: *run_tests
  stage: test
  image: ruby:2.3
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.sinatra-1.4.x

ruby26-sinatra14:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.sinatra-1.4.x

ruby23-sinatra20:
  <<: *run_tests
  stage: test
  image: ruby:2.3
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.sinatra-2.0.x

ruby26-sinatra20:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.sinatra-2.0.x

ruby26-sinatra-edge:
  <<: *run_tests
  stage: test
  allow_failure: true
  image: ruby:2.6
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.sinatra-edge

ruby23-grape:
  <<: *run_tests
  stage: test
  image: ruby:2.3
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.grape

ruby26-grape:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.grape

ruby26-grape013:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.grape
    GRAPE_VERSION: "~> 0.13.0"

ruby26-grape110:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.grape
    GRAPE_VERSION: "~> 1.1.0"

ruby26-grape120:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.grape
    GRAPE_VERSION: "~> 1.2.0"

ruby26-grape-edge:
  <<: *run_tests
  stage: test
  allow_failure: true
  image: ruby:2.6
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.grape
    GRAPE_VERSION: edge

ruby26-rails42-tilt:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.rails-4.2.x
    TILT_VERSION: 1.4.1

ruby26-sinatra14-sequel:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.sinatra-1.4.x
    SEQUEL_VERSION: 4.34.0

ruby26-rails42-mongo:
  <<: *run_tests
  stage: focus
  image: ruby:2.6
  services:
    - mongo:3.4-jessie
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.rails-4.2.x
    TEST_MONGO_INTEGRATION: "true"

ruby26-rails42-mongoid:
  <<: *run_tests
  stage: focus
  image: ruby:2.6
  services:
    - mongo:3.4-jessie
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.rails-4.2.x
    TEST_MONGO_INTEGRATION: "true"
    MONGOID_VERSION: "~> 4.0"

ruby26-rails42-elasticsearch:
  <<: *run_tests
  stage: focus
  image: ruby:2.6
  services: 
    - elasticsearch:5-alpine
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.rails-4.2.x
    TEST_ELASTICSEARCH_INTEGRATION: "true"
    ELASTICSEARCH_URL: "http://elasticsearch:9200"

ruby26-rails51-sidekiq4:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.rails-5.1.x
    SIDEKIQ_VERSION: 4.2.10

ruby26-rails51-sidekiq-none:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.rails-5.1.x
    SIDEKIQ_VERSION: "none"

ruby26-rails42-ams83:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.rails-4.2.x
    AMS_VERSION: "~> 0.8.3"

ruby26-rails42-ams95:
  <<: *run_tests
  stage: test
  image: ruby:2.6
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.rails-4.2.x
    AMS_VERSION: "~> 0.9.5"

ruby26-rails42-ams-edge:
  <<: *run_tests
  stage: test
  allow_failure: true
  image: ruby:2.6
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.rails-4.2.x
    AMS_VERSION: edge

ruby-head-rails52:
  <<: *run_tests
  stage: test
  allow_failure: true
  image: rubocophq/ruby-snapshot:latest
  variables:
    RUBY_GEMFILE: gemfiles/Gemfile.rails-5.2.x
